# Generated by Django 4.1.2 on 2022-10-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='jumps',
            field=models.IntegerField(default=0),
        ),
    ]
