# Generated by Django 4.1.2 on 2022-11-10 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('convert_link', '0003_remove_user_title_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlink',
            old_name='updated_at',
            new_name='last_jump_at',
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
