# Generated by Django 4.1.2 on 2022-11-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_link', '0004_rename_updated_at_shortlink_last_jump_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='owner',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='source_link',
            field=models.URLField(),
        ),
    ]
