# Generated by Django 4.1.2 on 2022-11-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_link', '0005_alter_shortlink_owner_alter_shortlink_source_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='last_jump_at',
            field=models.DateTimeField(null=True),
        ),
    ]
