# Generated by Django 4.1.2 on 2022-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_link', '0006_remove_shortlink_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'verbose_name': 'Коротке посилання', 'verbose_name_plural': 'Короткі посилання'},
        ),
        migrations.RemoveField(
            model_name='shortlink',
            name='deleted',
        ),
        migrations.AddField(
            model_name='shortlink',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Видалено'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='jumps',
            field=models.IntegerField(default=0, verbose_name='Кількість переходів'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='last_jump_at',
            field=models.DateTimeField(null=True, verbose_name='Останній перехід'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='owner',
            field=models.CharField(max_length=15, verbose_name='ID/IP власника'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_link',
            field=models.CharField(max_length=42, verbose_name='Коротке посилання'),
        ),
    ]
